### ISSUE TITLE
Create a migration path/tool for RAML 1.0 to RAML 0.8

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#10]
For some number of months, tooling/infrastructure/platform vendors like MuleSoft will not support RAML 1.0, only RAML 0.8. But we want users to start using RAML 1.0 as soon as it's released. We should create a migration path and tooling to allow downgrading a RAML spec from 1.0 to 0.8 so it can be consumed by those tools/platforms. This would indicate to the user what features will be lost, take workarounds like reducing the examples to a single example, etc..

**Comment by sichvoge** [comment]
Shouldn't be in this repository. BTW, we have a "migration guide" inside the raml-spec repo in Github.

**Comment by philipp-berger** [comment]
I still see here an issue... everything is still for 0.8
It already took me more than 2 hours to generate html from my raml1.0...
Would be nice if anybody can assist or point me to a converter from raml1.0 to raml0.8

**Comment by pjanuario** [comment]
@philipp-berger I had exactly the same problem, the tools don't seem ready for 1.0. The sideeffec of it is that it seems the ecosystem isnt entirely aligned! :( after some tries with dev branches and different projects to generate html from raml, I just gave up and considering API Blueprints for now or just use 0.8! :(

**Comment by sichvoge** [comment]
I don't understand what you are saying completely. I do agree that there is development and tools are currently keeping up with the spec changes. There is progress, for example, recent development on raml2html (see https://twitter.com/mixedcase/status/781842423844593665). 

What else is "not entirely aligned"?

**Comment by pjanuario** [comment]
@sichvoge sorry about not explaining myself entirely.
So I am starting a new API and I was using RAML 1.0 when i tried to generate HTML documentation from i was unable too, after reading some forums and several questions, several people were with similar problems.
But in the past few days, after trying raml2html and ramlo projects I finally made it work. The catch it's that will only work using a beta npm package and i didn't found this in readme only by looking into the development branches and chagelogs. :/
But i made it work with raml2html and raml-mockup. 😄 

So my problem is solved for now.
