### ISSUE TITLE
XML/XSD validation toolset is urgently needed

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#11]
Our current validation for XML (using DOM parser) is horrible we need to change it. (lets search if some pure javascript library exist).

**Comment by ddenisenko** [comment]
Relevant comments:

blakeembrey :
I'd be curious if a JS one exists, but the only one I've managed to use in tooling is https://github.com/polotek/libxmljs

**Comment by sichvoge** [comment]
@ddenisenko I remember we added that, right? Can you update the ticket.

**Comment by ddenisenko** [comment]
Implemented, now XSDs and XMLs are validated both in npm and browser versions.
