### ISSUE TITLE
Auto-completion seems to be broken

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#118]
When trying to set a type I only get suggestion for `object` in any context. 

![image](https://cloud.githubusercontent.com/assets/498114/12859825/90ff613e-cc0d-11e5-9f7b-3992a2101d87.png)

Configuring it to `string`, though, does not end in a validation error. So it seems there is something wrong with the auto-completion.

**Comment by ddenisenko** [comment]
Bug fix is published in 0.8.19.
