### ISSUE TITLE
Adding resource types crashes atom

### ISSUE THREAD

**Issue by redndahead** [mulesoft/api-workbench#121]
I'm trying to follow the example here: http://docs.raml.org/specs/1.0/#raml-10-spec-resource-type-and-trait-parameters

I can get about this far:
`resourceTypes:
  - collection:
      get:
        responses:
          200:
            body:
              type: <<r`

Then it hangs. I've tried clicking wait a couple of times, but it stay's frozen. I have typed slowly to see where it hangs and it's as soon as you type "r". If I type fast enough I can get a few more letters in.

I've tried this on atom 1.4.3 and 1.5.0. Using api workbench v0.8.16

**Comment by ddenisenko** [comment]
Reproducible in production version only. Thanks a lot for reporting this.

It is not about resource types, nor templates. Its when template parameter is used as a type.

This one will be fixed ASAP.

**Comment by ddenisenko** [comment]
Fix published in 0.8.17.

In short, we had a dependency on `xmldom` module of 0.1.19+ version. `xmldom` of a recent version 0.1.22 hangs when trying to parse a certain invalid XML, its 0.1.19 version does not hang.
