### ISSUE TITLE
Can't figure out how to fix $ref problems in schema

### ISSUE THREAD

**Issue by ProLoser** [mulesoft/api-workbench#122]
So I've been struggling for weeks trying to get the stupid errors about not being able to find schema references fixed. I have it working in abao, schema dereferencers, and other tools but not in workbench. I have no idea what it's using for the file path and abao just imports all the schemas ahead of time and indexes them by id (which is what I went with). So how do I get the schema ref validations to work?

<img width="1552" alt="screen shot 2016-02-10 at 2 46 16 pm" src="https://cloud.githubusercontent.com/assets/67395/12964454/132efde0-d005-11e5-8dc4-3a736acff8f8.png">

**Comment by ddenisenko** [comment]
Could you please provide RAML file, and schemas so we can check what's going on locally?

**Comment by scranen** [comment]
I'm having issues with schema resolution too, not sure if it's the same issue. Basically, I have not found a way to include a schema that references another schema. All example API's I checked don't use this feature (the NewRelic API for instance has a keyTransaction schema and a keyTransactionList; the keyTransaction type is not used in the latter, instead it is duplicated).

In my RAML spec:
```yaml
#%RAML 1.0
types:
  - MyType: { $ref: http://absolute.url/to.json#/MyType }
```

This is all okay, as long as MyType does not reference any other schema. Suppose the contents of to.json are as follows:
```json
{
  "MyType": { "$ref": "#/OtherType" },
  "OtherType": {}
}
```

This breaks resolution of MyType in the API workbench because it cannot find "#/OtherType". I have tried splitting to.json into MyType.json and OtherType.json to two different files and changing the reference to "OtherType.json", but that also fails. I have also in both cases tried referencing the other type with absolute URLs. Nothing seems to work.

The resolution fails when the API workbench is trying to validate my example response body against the type I specified. I get a warning: "Example does not conforms [sic] to schema:Content is not valid according to schema:Reference could not be resolved: #/OtherType #/OtherType"

**Comment by ddenisenko** [comment]
@scranen 
Actually, for me this one fails at the stage of initial reference resolving (it does not even go to http://absolute.url/to.json to find MyType.
```RAML
#%RAML 1.0
types:
  - MyType: { $ref: http://absolute.url/to.json#/MyType }
```

If I use reference inside include, like this:
```RAML
types:
  - MyType: !include http://absolute.url/to.json#/MyType
```
then it fails as you described.

Generally, we have troubles with references, which should be fixed soon.

**Comment by scranen** [comment]
My bad, it was a long day. I am indeed using `!include` when this error occurs. 

Can you give me an indication of the time frame in which this might be fixed? I currently have a decision to make on whether to use Swagger or RAML for a potentially large project. I like RAML better as a specification language, but tool support for JSON-schema $refs is important for me.

**Comment by ddenisenko** [comment]
In about a week.

**Comment by ddenisenko** [comment]
Please check the latest release and let me know how it feels with regard to the references. Its not something finished, we had to work around some of the library bugs, but should be better now.

**Comment by scranen** [comment]
This seems to work for me, thanks!

**Comment by idefixcert** [comment]
I also have a schema resoloution Problem too, but only if I provide Examples:
```
--- Description
schemas:
  - EnumEntry: !include schemas/enumEntry.schema
  - Enum: !include schemas/enum.schema
/enum:
  type:
     readonlySingleObject:
       schema : Enum
       example: !include schemas/enum.sample
  is:
    - secured
--- enum.schema
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "description": "Representation eines einzelnen Enum Eintrags",
  "properties": {
    "name":  { "type": "string", "required": true },
    "language":  { "type": "string", "required": true },
    "laenge":  { "type": "string", "required": true },
    "enumEntries" : {"type":"array","items": {"$ref":"EnumEntry"}}
  }
}
--- enumEntry.schema
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "description": "Representation eines einzelnen Enum Eintrags",
  "properties": {
    "key":  { "type": "string", "required": true },
    "value":  { "type": "string", "required": true },
    "deleted":  { "type": "boolean", "required": true }
  }
}
---
Example does not conform to schema:Content is not valid according to schema:Reference could not be resolved:
.../raml_0.8/schemas/enum.schema#/EnumEntry .../raml_0.8/schemas/enum.schema#/EnumEntryat line 19 col 1

```

**Comment by ddenisenko** [comment]
@idefixcert , could you please provide the text of `enum.sample`?

**Comment by idefixcert** [comment]
enum.sample
```
{
  "name":  "swiftwcd",
  "language":  "de",
  "laenge":  "lang",
  "enumEntries": [
      {
      "key": "EUR",
      "value":  "EURO",
      "deleted":  false
      },
      {
      "key": "DM",
      "value":  "Deutsche Mark",
      "deleted":  true
      },
      {
      "key": "USD",
      "value":  "US Dollar",
      "deleted":  false
      }
  ]
}
```

**Comment by ddenisenko** [comment]
Thank you.

In order to make the reference working and pointing to `enumEntry.schema` file, please replace `{"$ref":"EnumEntry"}` in `enum.schema` file with `{"$ref":"enumEntry.schema"}`

**Comment by idefixcert** [comment]
ok thats right, but in this case the generator raml-for-jaxrs is not working.
so i renamed the schema from enumEntry.schema to EnumEntry and therfore i can reference it by {"$ref":"EnumEntry"}. 

Thanks

**Comment by ddenisenko** [comment]
Looks like we can close this one.
