### ISSUE TITLE
Console should extract security schema fields

### ISSUE THREAD

**Issue by mpmlj** [mulesoft/api-workbench#124]
Hi,

Please see the screenshots below.
When applying security schema ("CommonSchema"), I would expect the Console to use its parameters (pass through, key & secret as query params). However, Console is empty.
Current workaround is to duplicate queryParams (for example) along with a "securedBy" definition.

Here's some logic:
As far as as I have a required query parameter (API KEY) + one optional, as per RAML 1.0 specs for the "describedBy?" property I SHOULD describe them: "...As a best practice, even for standard security schemes, API designers SHOULD describe these properties of security schemes. Including the security scheme description completes an API documentation..."
This makes a separate description of the resource query parameters unnecessary and anyways, as per the specs, queryParameters is OPTIONAL.

So, if we have params/headers/etc in a security scheme, Console should use **them** for request composition (even if they also exist in the document body).

Thoughts?

P.S.
Also would be great if these fields are populated from corresponding "example" values.

Thank you,
D.

![screen shot 2016-02-11 at 12 12 10 pm](https://cloud.githubusercontent.com/assets/6718777/12984565/53a5cfea-d0bc-11e5-98da-46b8cde16bf7.png)
![screen shot 2016-02-11 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/6718777/12984564/53a43f22-d0bc-11e5-824b-46ac73ad1423.png)

**Comment by blakeembrey** [comment]
Looks like a duplicate of https://github.com/mulesoft/api-workbench/issues/104, but correct me if that's wrong.

**Comment by mpmlj** [comment]
@blakeembrey 
You are right. Sorry for posting a dupe. One difference though - execution priority if params are also defined in the main RAML file body.
Thanks
