### ISSUE TITLE
#%RAML 1.0 AnnotationTypeDeclaration : doesnt allow to include properties in annotation

### ISSUE THREAD

**Issue by thenanox** [mulesoft/api-workbench#134]
When creating an annotation in RAML master file, i dont have any problem adding properties into annotations:

![annotationok](https://cloud.githubusercontent.com/assets/4981277/13526836/0b621f76-e20b-11e5-80fc-bff67429569a.png)

However, when i try to externalize the annotation as a AnnotationTypeDeclaration, is not possible to use properties inside:

![annotationfail](https://cloud.githubusercontent.com/assets/4981277/13526854/1d338f32-e20b-11e5-99b5-284c03bcb75f.png)

**Comment by ddenisenko** [comment]
Reproducible, thank you for reporting this.

**Comment by ddenisenko** [comment]
Fixed. Fix should be published in 0.8.31.
