### ISSUE TITLE
#%RAML 1.0 DataType : not possible to include annotations

### ISSUE THREAD

**Issue by thenanox** [mulesoft/api-workbench#135]
Im trying to externalize a dataType in a #%RAML 1.0 DataType file and use annotations inside the file. the problem is the annotations declarations are not transfered from master to files included:

![userko](https://cloud.githubusercontent.com/assets/4981277/13526984/0917f2da-e20c-11e5-80d5-9b5e92814e5e.png)

So in order to do this, i though about using libraries, so im able to do this:

![userok](https://cloud.githubusercontent.com/assets/4981277/13527012/3faafbda-e20c-11e5-9b63-ebcabeacd657.png)

The main problem, is that libraries break the api that include this user raml, because i need to !include the user.raml and write something like _library.user_ to use the dataType.

I'm concerned about this issue https://github.com/raml-org/raml-spec/issues/226.

So my question is, is supossed to be done in libraries way and wait for the spec and workbench so libraries may be imported withour prefix? or is expected to add more functionality in order to include annotations in a #%RAML 1.0 DataType declaration?

**Comment by sichvoge** [comment]
In the next release candidate of 1.0, you will be able to use libraries inside a DataType fragment as well. Therefore you can create a library with all your annotations, include (use) it inside your DataType, and select the annotation you need. (see [raml-org/raml-spec#226](https://github.com/raml-org/raml-spec/issues/226)

Does that answer your question?

**Comment by thenanox** [comment]
Yeah, it is perfect. I thinks is the right way to go :)
