### ISSUE TITLE
Defining an array annotation type is not working

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#138]
As per spec, the value of the `annotationTypes` node is a map of key-value pairs where each key is a unique identifier for a specific annotation and its value just another type declaration plus additional facets.

So as per definition, the following should be allowed, but is not working:

![image](https://cloud.githubusercontent.com/assets/498114/13808505/404aaf4e-eb5e-11e5-959c-2786cccc152f.png)

The example above is just to highlight that a type declaration does not complain, but the one in the annotation type does.

**Comment by thenanox** [comment]
@sichvoge yeah i had this problem too when defining as an array in #137. I think annotations weren't prepared to work with arrays like that previously to delete AllowMultiple

**Comment by sichvoge** [comment]
Yep, I will make sure that it get's resolved.

**Comment by VasiliyLysokobylko** [comment]
Looks like fixed.

**Comment by ddenisenko** [comment]
Works in `code` branch, which should be published in 0.8.30.
