### ISSUE TITLE
property 'is' must be an array in examples

### ISSUE THREAD

**Issue by ruoqianfengshao** [mulesoft/api-workbench#149]
There is an error when I follow with getting started examples:

![image](https://cloud.githubusercontent.com/assets/2928664/14556615/9c0dfa2c-032b-11e6-8d5a-1ea07bbfe02c.png)

And then I find the correct usage of  property `is` in doc [https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#query-strings](https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#query-strings) 
``` raml
  is: [ filterableByPrice ]
```

Is there a mistake in getting started docs?

**Comment by sichvoge** [comment]
All the example in the getting started are for 1.0, and 1.0 is saying the same. Seems to be an issue in the docs. Thanks for reporting.

**Comment by ddenisenko** [comment]
Fixed documentation, will be published on the next workbench.com update.
