### ISSUE TITLE
New resources appears after documentation section

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#15]
1)Open Slack project: https://github.com/raml-apis/Slack/tree/raml1.0
2)Create a new resource using wizard.
Result: New resource placed after documentation section.

**Comment by ddenisenko** [comment]
Fix should be available in 0.8.8.

**Comment by sichvoge** [comment]
0.8.8 is out, is this fixed?

**Comment by ddenisenko** [comment]
Yes, it works.
