### ISSUE TITLE
Error when parsing file system relative path

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-workbench#153]
I've installed api-workbench from github and reproduced the issue. I got error `Example does not confirm to schema: Content is not valid according to schema: Reference could not be resolved`

I've used following commands to install plugin:
```
git clone git@github.com:mulesoft/api-workbench.git
cd api-workbench
apm link .
apm install
```

I have following files: `api.raml`
```yaml
#%RAML 0.8
title: Relative paths example test
version: v1
baseUri: http://localhost:9001
schemas:
  - complex: !include schemas/complex.json

/:
  post:
    body:
      application/json:
        schema: complex
    responses:
      201:
        body:
          application/json:
            schema: complex
            example: !include examples/complex.json
```
schemas/complex.json
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "simple": {"$ref": "simple.json"},
    "name": {"type": "string"}
  },
  "required": ["id","name"]
}
```
schemas/simple.json
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "string"
}
```
examples/complex.json
```json
{
  "simple": "test",
  "name": "Test"
}
```

Could you have a look please? It's hard to edit raml with false positive errors :(

**Comment by dreamflyer** [comment]
You forget '#' at the end of in ' {"$ref": "simple.json"}, ', it should be ' {"$ref": "simple.json#"}, '. But i think that we should support such cases and it should be treated as 'simple.json#' if no '#' provided. It already fixed and soon will be published.

**Comment by sichvoge** [comment]
@dreamflyer is that fixed?

**Comment by alvassin** [comment]
@sichvoge @dreamflyer it seems to be not to be fixed.

**Comment by sichvoge** [comment]
@alvassin can you make sure to raise that on the js parser. Its an issue with the parser.

**Comment by alvassin** [comment]
@sichvoge After it was discussed in https://github.com/raml-org/raml-js-parser/issues/140 i've made PR https://github.com/raml-org/raml-js-parser/pull/176 that provides new setting: `dereferenceSchemas`.

Raml parser would return all schemas dereferenced in case it is set to `true`.

**Comment by sichvoge** [comment]
the one you are using is the old parser that has not been used for the workbench. there is a new implementation that supports 0.8 and 1.0 [here](https://github.com/raml-org/raml-js-parser-2/).

**Comment by alvassin** [comment]
I can't see any mentions about 0.8 at raml-js-parser-2. Are you sure it supports raml 0.8 itself?

**Comment by sichvoge** [comment]
I am very sure about that ;)

**Comment by sichvoge** [comment]
Changed the readme to make that a bit more clear ;)

**Comment by ddenisenko** [comment]
Works now. It complaints regarding missing "id" property, which is actually missing.
