### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lowLevel' of null

### ISSUE THREAD

**Issue by hckhanh** [mulesoft/api-workbench#154]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24

### Stack Trace

Uncaught TypeError: Cannot read property 'lowLevel' of null

```
At C:\Users\hoang\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\mutators.js:321

TypeError: Cannot read property 'lowLevel' of null
    at Object.addToNode (C:\Users\hoang\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\mutators.js:321:22)
    at ASTNodeImpl.add (C:\Users\hoang\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\highLevelImpl.js:994:18)
    at Object.action (C:\Users\hoang\.atom\packages\api-workbench\main.js:4:15965)
    at C:\Users\hoang\.atom\packages\api-workbench\main.js:4:25945
    at C:\Users\hoang\.atom\packages\api-workbench\node_modules\atom-ui-lib\dist\UI.js:389:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (C:\Users\hoang\.atom\packages\api-workbench\node_modules\atom-ui-lib\dist\UI.js:389:31)
```

### Commands

```
     -1:38.8.0 api-workbench:Create new Response (label.icon.icon-primitive-dot.text-warning)
     -1:08.0 api-workbench:popular-apis (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:00.5.0 api-workbench:editor-tools (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.2.0 api-workbench:Add new resource (atom-text-editor.editor.is-focused)
     -0:26.7.0 api-workbench:Add new method (label.icon.icon-primitive-square.text-highlight)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
linter, v1.11.4
minimap, v4.22.1

# Dev
No dev packages
```

**Comment by f1xmAn** [comment]
This bug affects me too but I have Ubuntu 15.10 (amd64).

**Comment by ddenisenko** [comment]
Could you please describe what you were doing before getting this error?
Did you have RAML editor opened? What was RAML contents? Did you activate any action/ type something in the editor?

**Comment by TimonSotiropoulos** [comment]
This issue has also appeared for me. I was attempting to create a method from a resource I had created on a raml file when the error was thrown. 

Basically just:

Created a new resource in the Outline window
Right clicked the new resource and selected add method
Selected a GET method with the following options:

Method: GET
BODY
Generate Default Media Type: application/json
Generate defauly body with type: object
RESPONSE
Status Code: 200
Generate default res media type: application/json
Generate default res with type: object

Any more information let me know, happy to try and dig up some more info.

**Comment by ddenisenko** [comment]
Looks working.
