### ISSUE TITLE
Details panel does not render type correctly

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#157]
This might be related to https://github.com/raml-org/raml-js-parser-2/issues/119. I am using that same example and seeing

![image](https://cloud.githubusercontent.com/assets/498114/14703865/feca7e38-07a9-11e6-878f-8705df66321b.png)

Seems like the bug in the parser influences the rendering in details, but also where is the marker on line 19 for the error?

Some further analysing using shortcut `?` and also removing `[]`.

![image](https://cloud.githubusercontent.com/assets/498114/14703990/8aca59d0-07aa-11e6-8898-aae131473000.png)

![image](https://cloud.githubusercontent.com/assets/498114/14704008/9be23bb6-07aa-11e6-90e7-dd426e9cac0c.png)

All that worked with 0.8.23 before introducing the new parser.

**Comment by ddenisenko** [comment]
Fixed, the fix will be published in 0.8.30.
