### ISSUE TITLE
'types' node is unknown

### ISSUE THREAD

**Issue by tebs1200** [mulesoft/api-workbench#163]
I'm trying to create a very basic API spec but I'm getting an error at the third line after the latest update (0.8.26). The `types:` node appears to be unknown. Here's my file:

    #%RAML 1.0
    title: Example API
    version: 0.0.1

    types:

See the attached screenshot for the error:
![screen shot 2016-04-28 at 4 39 24 pm](https://cloud.githubusercontent.com/assets/9997294/14877424/453b4b34-0d60-11e6-8ff8-3e6900848a7c.png)

**Comment by VasiliyLysokobylko** [comment]
Fixed in the 0.8.30
