### ISSUE TITLE
errors emitted when baseUri begins with a parameter

### ISSUE THREAD

**Issue by mutsys** [mulesoft/api-workbench#165]
According to the RAML 1.0 spec, baseUri will accept a level 1 URI template. However, if the template begins with a parameter, api-workbench emits this error.

`TypeError: uriValue.indexOf is not a function`

Here is an example of one such valid template that causes api-workbench to choke:

`{paramA}/{paramB}`

if I prepend this with any character than a `{`, api-workbench accepts the value for baseUri. Examples of "valid" templates:

`a{paramA}/{paramB}`
`/{paramA}/{paramB}`

A reading of RFC 6570 finds no mention of any restriction that says a template may not begin with a paramter. Of course, this issue may be due to the underlying js parser rather than api-workbench itself.

**Comment by ddenisenko** [comment]
This works now, if you put `{paramA}/{paramB}` into qoutes: `baseUri: "{paramA}/{paramB}"`.
Omitting quotes makes it invalid from YAML parser's point of view.
