### ISSUE TITLE
Update API Workbench to support RAML 1.0 RC2

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#170]
Currently, the workbench uses an older version of the JS parser that does not fully support the RC2 changes. Since the RC2 spec is out since last week with a pre-release version of the RC2 parser, we should update the workbench accordingly to close the gaps. 

The current plan to do that till Monday, 16th May!

**Comment by sichvoge** [comment]
@ddenisenko where are we? do we support the latest spec changes since the last workbench release? can you confirm before we close that.

**Comment by ddenisenko** [comment]
The code is published to `code` branch of this repository: https://github.com/mulesoft/api-workbench/tree/code

Installation instructions for development version:
1. `git clone https://github.com/mulesoft/api-workbench.git --branch code`
2. `cd api-workbench`
3. `apm install`
4. `apm link`

The code is still under testing/bug fixing, the first RC2 release should be coming in the beginning of the next week.

**Comment by sichvoge** [comment]
We are about to finish our current QA tests this week and plan to publish the update to APM by next week Monday.

**Comment by ddenisenko** [comment]
This is published in 0.8.30.
