### ISSUE TITLE
Datetime type not supported

### ISSUE THREAD

**Issue by szank** [mulesoft/api-workbench#171]
Datetime type does not seem to be supported. Could you please fix that ? Version 0.8.28

<img width="654" alt="screenshot 2016-05-13 14 45 50" src="https://cloud.githubusercontent.com/assets/773802/15250094/f0c14ea2-191a-11e6-88f3-0d3860f9a841.png">

**Comment by sichvoge** [comment]
Hi @szank, thanks for raising the issue. The workbench does not completely support RC2 yet. There are some modification we need to do and the parser was published a couple of days ago. See [here](https://github.com/mulesoft/api-workbench/issues/170). So have a little bit patient with us ;)

**Comment by VasiliyLysokobylko** [comment]
Fixed in the 0.8.30
