### ISSUE TITLE
Auto-completion with the latest version seems to be off

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#176]
As you can see in the image below, auto-suggestion seems to be a bit off. 

![image](https://cloud.githubusercontent.com/assets/498114/15366685/66ac364e-1d1d-11e6-9e8f-6e25e64e7d05.png)

Its not the only position. The completion also suggest a type `date` which is not in the spec anymore.

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 0.8.32.
