### ISSUE TITLE
Format not working in Data Weave

### ISSUE THREAD

**Issue by osmanjabri** [mulesoft/api-workbench#177]
Hi Expert
I am trying to use format function in a Data weave mapping and it is working in one mapping but not in other.

I have 2 mappings
 - Json to XML conversion (format is working)
 - XML to Json conversion (format is not working)

I am using same statement is both the Transformation step, no difference.
-----> value : "34.999" as :number {format: '#.##'},
It gives me value as 35 in (Json to XML transformation step)
but gives me value as 34.999 in (XML to Json transformation step).

Can any one help me with this issue??

Thanks and Regards
Osman

**Comment by sichvoge** [comment]
Hi @osmanjabri, you might want to go to [Mulesoft's forums](https://forums.mulesoft.com) and post your issue there. The API Workbench is not Anypoint Studio ;)
