### ISSUE TITLE
"uses" library reference works differently on Linux and Windows

### ISSUE THREAD

**Issue by amammes** [mulesoft/api-workbench#181]
I have a dual boot Win10/Ubuntu 16.0.4 LTS laptop. I use Atom 1.7.4 with api-workbench 0.8.28 on both platforms.

If I open the same exact project in both platforms, the "uses" section behaves differently. The Linux version wants a map and the Windows version want me to use !include.

I have tried reinstalling and updating on Windows to no avail. Can someone help me understand what's going on?

Check out this sample:

```
#%RAML 1.0
title: API used to test broken features
mediaType: application/json

uses:
  # the following line is ok on api-workbench 0.8.28 on Windows 10
  # Linux version complains that this must be a map in RAML 1.0 
  myTypes: !include brokenLibrary.raml 

  # the following line is ok on api-workbench 0.8.28 on Linux.
  # Windows version complains thay myTypes cannot be a scalar
  # myTypes: brokenLibrary.raml 
  
/:
  get:
    responses:
      200:
        body:
          type: myTypes.myType
          example: "somevalue"

```

**Comment by amammes** [comment]
I found that my Windows api-workbench depends on "raml-1-parser": "0.2.6" and the Linux version on "0.2.12". That would explain the different parsing behavior.

I don't understand why they are using different components if the version number is the same.

**Comment by ddenisenko** [comment]
@amammes did you happen to install 0.2.28 on Windows considerably earlier than on Linux?

**Comment by amammes** [comment]
@ddenisenko yes, I did. However after that I uninstalled api-workbench, atom, and deleted .atom recursively in my user profile. Then I reinstalled everything. I have always installed using atom's package manager instead of using git clone and apm install.

Now I have installed 0.8.29 using git clone on both platforms and they behave the same because they are using the same parser.
