### ISSUE TITLE
Switching outline tabs make 'grouping arrow' disappears

### ISSUE THREAD

**Issue by yamsellem** [mulesoft/api-workbench#205]
Release 0.8.30 with atom 1.8.0

Switching outline tabs manually make the 'grouping arrow' disappearing from tabs.
It should look like this:

![before](https://cloud.githubusercontent.com/assets/606754/15997288/879cfa0e-3132-11e6-9a48-7e36565d68af.png)

But ends like that:

![after](https://cloud.githubusercontent.com/assets/606754/15997289/8977327c-3132-11e6-8d2b-c23f1194bda8.png)

**Comment by ddenisenko** [comment]
Fix published in 0.8.31.
