### ISSUE TITLE
Error: specifying unknown facet:properties

### ISSUE THREAD

**Issue by ericleestewart** [mulesoft/api-workbench#219]
I'm getting the following error opening the attached "mailer/voucher_report.raml".

> Error: specifying unknown facet:properties

It's inheriting types and traits from base.raml. Another interesting note is that if I combine all the separate files into a single file, the error goes away.

I'm running Atom version 1.7.4 and Workbench version 0.8.31 on Mac OS X 10.11.5 (15F34).

[raml-example.zip](https://github.com/mulesoft/api-workbench/files/327999/raml-example.zip)

**Comment by sichvoge** [comment]
Can you try the latest version for the workbench 0.8.32

**Comment by ddenisenko** [comment]
Looks to work now.
