### ISSUE TITLE
disable validation for non-RAML files

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#220]
Currently every single file that seems to use the either `*.raml` or `*.yaml` extensions (maybe more) gets validated and produces unnecessary errors. The specification states that a RAML document always starts with `#%RAML <version>` and these should be the files that get validated. Everything else should get ignored. Same principle that the Mulesoft API Designer uses.

**Comment by ddenisenko** [comment]
Implemented. This will be published in 0.8.33
