### ISSUE TITLE
Add information on setting up the development environment

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#222]
We definitely need to add information on setting up a dev environment to help people who want to contribute. That should be inside the REAMDE where we could mention step by step what they need to do and also maybe some suggestions on development IDEs. Intelij is really good but they can also use Atom with the Typescript plugin.

**Comment by ddenisenko** [comment]
Done. Instructions are added to Contribution Guide, which is referenced from readme.
