### ISSUE TITLE
Add ui-libs to the source build

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#224]
We do depend on https://github.com/mulesoft-labs/ui-libs NPM module. 

In order to improve CI, we should be adding the procedure of building API Workbench against this library latest sources instead of (currently) NPM module to the build. 

This will also affect API Workbench dev. environment installation.

**Comment by ddenisenko** [comment]
Done.

**Comment by sichvoge** [comment]
@ddenisenko can you explain what the module is used for?

**Comment by ddenisenko** [comment]
The module is used to display UI. It provides an hierarchy of UI components being translated into HTML/DOM.
