### ISSUE TITLE
Error when installing api-workbench in Atom

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#25]
This issue tracks the following problem when trying to install the api-workbench package into Atom:

```
npm WARN peerDependencies The peer dependency webpack@^1.4.2 included from string-replace-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
.......

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

**Comment by sichvoge** [comment]
Solution that worked for me: check if you have `npm` installed, if not please do that.

**Comment by sichvoge** [comment]
Seems there is still a problem for some people. I will keep it open.

**Comment by kokujin** [comment]
Same problem here. I am using Node and NPM for several other things so NPM cant be the problem

**Comment by sichvoge** [comment]
What OS do you use? For me it happens only in Windows.

**Comment by wags** [comment]
I encountered the same problem. I tried the installation at an elevated command prompt with `apm install api-workbench` and through the Install Packages screen in Atom. I am on a PC running Windows 10 Pro.

**Comment by cuctc** [comment]
Also having this problem trying to install in Windows. Have Node and NPM installed. Really looking to get going with RAML 1.0

**Comment by sichvoge** [comment]
OK - seems to be an issue on Windows only. Tried CentOS and Mac -> it worked. We investigate further.

**Comment by kokujin** [comment]
I am using Elementary OS (Ubuntu 14.04)

**Comment by sichvoge** [comment]
Can you guys try to execute the following (please close Atom before):

```
apm clean
apm rebuild module cache
```

And open Atom again. Let me know if that works for anyone.

**Comment by sichvoge** [comment]
Hi guys, just found that thread - seems to be a Windows problem: https://github.com/nodejs/node-gyp/issues/629.

**Comment by wags** [comment]
@sichvoge nice find. Thank you for sharing that.

**Comment by sichvoge** [comment]
If anyone solve that - please let us know. :)

**Comment by jamesdonelan** [comment]
I ran into the same issue and I'm on a Mac OS X, so doesn't appear to be a windows-only issue.

#running from command line:
apm install api-workbench
...
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rx/v183dgy9757b8p8w1lgp4m080000gp/T/apm-install-dir-115103-65689-sd7xzu/npm-debug.log

**Comment by jamesdonelan** [comment]
I ran into the same issue and I'm on a Mac OS X, so doesn't appear to be a windows-only issue.

#running from command line:
apm install api-workbench
...
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rx/v183dgy9757b8p8w1lgp4m080000gp/T/apm-install-dir-115103-65689-sd7xzu/npm-debug.log

**Comment by sichvoge** [comment]
@jamesdonelan can you try run `apm rebuild module cache` on Mac -> that worked for me.

**Comment by sichvoge** [comment]
Guys, I am using a VM for my Windows that I don't own. Could someone try https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

**Comment by jamesdonelan** [comment]
@sichvoge tried it but no joy.

**Comment by mauroflores** [comment]
Hi guys, I had the same issue with Windows 10, it got solved doing this:
* Get Python v2.7.3
* Get Visual Studio  C++ 2013 Express
* Restart Atom
* Install api-workbench

Python version is important

https://github.com/nodejs/node-gyp#installation

**Comment by sichvoge** [comment]
ah ok - that was a guess already that you need additional stuff to compile some dependencies - thanks for posting that.

**Comment by sichvoge** [comment]
@wags and @cuctc could you try the above fix and let me know if it works. We also have an installation page in our Wiki now https://github.com/mulesoft/api-workbench/wiki/Installation-Tips

**Comment by wags** [comment]
@sichvoge I got it to work, and it was OK with Python version 2.7.10 (but not Python 3.5.0). Thanks.

**Comment by sichvoge** [comment]
Cool - we are currently working on trying to remove the dependencies to these native libs

**Comment by cuctc** [comment]
It appears to have installed correctly for me now as well. I went with 2.7.10 based upon @wags success and it seems to be okay. Thanks for the quick responses today

**Comment by fmezas** [comment]
even after `apm clean` and `apm rebuild module cache` it's still failing for me in os x. Attaching log:
[log.txt](https://github.com/mulesoft/api-workbench/files/26550/log.txt)

**Comment by sichvoge** [comment]
In OS X you might have to install XCode and the cmd line tools

http://stackoverflow.com/questions/19605862/unable-to-use-xcodebuild-on-mavericks-with-command-line-tools-installed

We are working on removing some of the native deps - will keep you all updated.

**Comment by jamesdonelan** [comment]
I'm running into the same issue as @fmezas. I have xcode command line tools and python 2.7.10 installed.

**Comment by sichvoge** [comment]
We are trying to remove some of the native deps. Hope that will help everyone.

**Comment by blakeembrey** [comment]
@sichvoge Thanks! I spent a while and removed some native dependencies. Certain features are currently disabled, which used those dependencies, but the core is hopefully installable now :smile: Please let me know if there are errors occurring still, and post the log here to inspect.

**Comment by fmezas** [comment]
@sichvoge @blakeembrey I was able to install version 0.8.3 in os x. thanks for fixing the problem

**Comment by sichvoge** [comment]
brilliant!

**Comment by ddenisenko** [comment]
Closing as resolved.

**Comment by kokujin** [comment]
Why should this be marked as closed? I still have the problem

**Comment by sichvoge** [comment]
Did you try version 0.8.5?

**Comment by ddenisenko** [comment]
@kokujin  Please let us know if installing 0.8.5 helps. If not, please reopen #28 (which is about Ubuntu) and post the error you are getting there.
