### ISSUE TITLE
Issue with "Get APIs from -> Popular APIs (Community)" in Windows

### ISSUE THREAD

**Issue by donaldgray** [mulesoft/api-workbench#251]
I am running Api-Workbench on Windows 7 machine using Atom 1.8.0 and Workbench 0.8.33.

Whenever I try to use the Get APIs from -> Popular APIs (Community) functionality I get the error 

> GIT is required to clone APIs. Please install GIT

I have GIT installed and can run `git version` from any command prompt and get result back (v2.7.2.windows.1).

**Comment by stephrouleau** [comment]
I have the exact same issue. Have installed Atom through Chocolatey, and from atom.io

I am running Windows 10 x64.

**Comment by ddenisenko** [comment]
@KonstantinSviridov could you please try reproducing it

**Comment by KonstantinSviridov** [comment]
Yes, it's reproduced

**Comment by KonstantinSviridov** [comment]
to be released in 0.8.39

**Comment by olenapavlenko** [comment]
I am still able to reproduce it - 0.8.48
could you look at it again?
