### ISSUE TITLE
Referencing a nonexisting schema with !include leads to a new file

### ISSUE THREAD

**Issue by alien0matic** [mulesoft/api-workbench#258]
We're doing something like this:
`schemas:
  - error: !include schema_error.json`
This is ok as long as "schema_error.json" exists.
If I put something in the include that isn't a file, the file gets created.
So putting this in the raml:
`schemas:
  - error: !include not_available.json`
I end up with a file "not_available.json" in the same folder as my raml and this file includes the line "can not resolve not_available.json"

This happens a lot and I have a huge amount of junk files cluttered all over my workplace, rendering the tool nearly useless as I have to clean up after it.

**Comment by ddenisenko** [comment]
If I got it right, the point of the bug was that adding an include pointing to the unexisting schema file was creating an empty file with that name. It was fixed.
