### ISSUE TITLE
When using example underneath body, no | is added

### ISSUE THREAD

**Issue by jamesontriplett** [mulesoft/api-workbench#273]
Coding a bunch of APIs, I've noticed one very annoying feature.  

Creating a tree like this: 
`    post:  `
`        body:`
`          application/json:`
`            example: |`
`              {...`

means I basically type: 
"po (enter)"
"bo (enter)
"ap (enter)
"ex (enter) (up arrow) (side arrows...) | (enter)" or do a mouse click on the line previous
it also causes an immediate validation error. And takes 10x as long as the last 4 lines of code.

It would be REALLY AWESOME, if the example added a | to the end of the line, or else didn't do a carriage return so I can add it myself.  The hideously annoying part is going back to the end of the previous line and adding the | character and then continuing.

**Comment by sichvoge** [comment]
I agree that's really annoying. Any help is very appreciated :)

**Comment by dreamflyer** [comment]
will be published in suggestions v0.0.19 release
