### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by spezzino** [mulesoft/api-workbench#277]
[Enter steps to reproduce below:]
1. Open .raml file
2. Click on any line

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.35
### Stack Trace

Uncaught TypeError: Cannot read property 'parent' of null

```
At /Users/aaaa/.atom/packages/api-workbench/main.js:3

TypeError: Cannot read property 'parent' of null
    at e.getNodePType (/Users/aaaa/.atom/packages/api-workbench/main.js:3:11335)
    at e.setSelection (/Users/aaaa/.atom/packages/api-workbench/main.js:3:11479)
    at t.updateViews (/Users/aaaa/.atom/packages/api-workbench/main.js:1:13511)
    at /Users/aaaa/.atom/packages/api-workbench/main.js:1:8453
```
### Commands

```
  2x -4:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:30.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.35
linter, v1.11.14
linter-raml-myrules, v0.0.6

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please provide RAML file to reproduce?

**Comment by velchev** [comment]
any update guys...

**Comment by ddenisenko** [comment]
@velchev It depends on what causes the issue. There is no RAML sample to reproduce. There is a known incompatibility between API Workbench and linter-raml-myrules atom packages, so if you encounter this issue with all RAML files, try uninstalling linter-raml-myrules package and see if it helps.

Not sure if that is the case with this ticket until we get RAML sample.
