### ISSUE TITLE
Problems with RAML Editors Tools Pane (details) and Schemas & Types Tab 

### ISSUE THREAD

**Issue by dberlind** [mulesoft/api-workbench#283]
Hey all, attached is a screenshot.. it shows the Details pane (activated by picking Open RAML Editor Tools) as being completely blank. It was showing some information yesterday. For example if I clicked on "application/json:" somewhere in the body of my RAML file, it would show the specified example (but strangely, not any specified schemas). Now, the Details pane shows nothing at all (no matter how many times I close the design or Atom altogether).  Also, you'll note that the Schemas & Types tab is equally blank. I'm assuming if you've go schema statements and types in your RAML file, it will find those and populate this tab with some information? Maybe I've got that wrong. 

![optimizedcoffeeapi_raml_ __users_davidberlind_raml_coffeeapi](https://cloud.githubusercontent.com/assets/6643130/17344800/713ceca8-58d1-11e6-8861-5c7d213a8585.jpg)

**Comment by xojins** [comment]
Same here. This was working 2 days ago for me when I first created the RAML project. Yesterday and today the RAML Editor Tools are not displaying anymore.

I tried to create a new RAML project to see if that restores the pane, but I'm running into the [Create Project Bug](https://github.com/mulesoft/api-workbench/issues/281).

The only thing that changed was I updated Atom to 1.9.2 this morning, but it did not fix it.

Anyone have a workaround?

**Comment by ddenisenko** [comment]
Yes, it looks like the latest Atom update brought us something breaking details. We'll try to restore it fast.

**Comment by sichvoge** [comment]
@dreamflyer @ddenisenko Can you explain what the problem was pls.

**Comment by ddenisenko** [comment]
The fix is published in 0.8.36. Please restart Atom after update.

**Comment by dberlind** [comment]
Thank you @ddenisenko. I have installed the fix and can confirm that the fix is operational. Under separate cover, I will file some commentary about the Outline and Details pane in terms of usability issues that I believe need to be addressed.
