### ISSUE TITLE
Tabs in Details Pane

### ISSUE THREAD

**Issue by dberlind** [mulesoft/api-workbench#285]

**Comment by ddenisenko** [comment]
Could you please feel the description.

**Comment by dberlind** [comment]
I'm sorry @ddenisenko. I don't recall what the issue is here and am surprised that I somehow posted an empty issue. I seem to recall that the Details Pane wasn't behaving as expected in some context. For example, if I'm on a node that says the following:

`post:
    description: blah blah blah
    body:
       application/json:
            schema: <insert some schema name that was included earlier at the top>
            example: !include examples/examplePost.json
`

And then I cursor over the schema or the example, I don't get anything in the details pane. 

That might have been it.

**Comment by ddenisenko** [comment]
Okay, looks like a bug.

**Comment by dreamflyer** [comment]
will be published in v0.8.39.
