### ISSUE TITLE
Schemas and Types Tab in Outline Pane and Details Pane

### ISSUE THREAD

**Issue by dberlind** [mulesoft/api-workbench#287]
Hey all,

My Schemas and Types tab in the Outline is consistently blank. Is there a way for the Schemas and Types tab to better react to the node that that cursor is positioned over? Or react at all?

For example, if I'm currently at the RAML root, and have a Schemas node in the root, shouldn't the Schemas and Types tab list those schemas? 

Also, the Details pane seems to respond appropriately when I cursor to an individual schema listing in the root, but does not respond when I cursor to a schema specification that's nested inside a node. 

For example:

![image](https://cloud.githubusercontent.com/assets/6643130/17442735/33e0ff08-5b05-11e6-8192-883ae1d905c1.png)

But ..

![image](https://cloud.githubusercontent.com/assets/6643130/17442780/8597cfb6-5b05-11e6-987b-fb1658596f6b.png)

Meanwhile..

![image](https://cloud.githubusercontent.com/assets/6643130/17442877/da752d30-5b05-11e6-8798-4864b7027a36.png)

**Comment by ddenisenko** [comment]
I agree, it would be good to display schema in these cases.

**Comment by ddenisenko** [comment]
Looks working now.
