### ISSUE TITLE
queryParameters 's 'example' can not pass raml validation

### ISSUE THREAD

**Issue by geosmart** [mulesoft/api-workbench#291]
use `#%RAML 0.8` ,a resource can not pass validation!
```raml

/single-query-record/{code}:
    uriParameters:
        code:
            displayName: code
            description: "服务编码"
            type: string
            required: false
            repeat: false
    post:
        description: "数据服务单笔查询"
        queryParameters:
            query...:
                displayName: query...
                description: |
                    query为动态字段：键值对查询参数；
                    根据【需求文档-数据API界面详情】中表单中文字段 ，找到对应【商户站数据服务一期接口文档】中的服务请求报文体（body）中的字段名
                type: string
                required: true
                example: |
                  {
                      "bankNo": "666666666666666666",
                      "name": "测试",
                      "idType": "01",
                      "idNo": "330110199900000000",
                      "reqType": "01"
                  }
        responses:
            "200":
                description: json串
            "400":
                description: "请求失败，参数错误"
```

run error：Error
```raml
string is expectedat line 60 col 17
Error
string is expectedat line 59 col 17
```

example: | is on line 59

**Comment by sichvoge** [comment]
Seems it is correct as the parser is validating the `example` as a JSON. But it is flagged as a warning only. Is an instance of `query...` always different and is that why you did not describe all the properties and instead use string?

**Comment by geosmart** [comment]
@sichvoge the query...  param is dynamic, so I just give an json example ,but the api-workbench say something is error!

**Comment by sichvoge** [comment]
I only get a warning from the api-workbench with your example. So you can ignore it. 

![image](https://cloud.githubusercontent.com/assets/498114/17618129/e552a384-6075-11e6-8fc7-9e747e0d9846.png)

The problem is that the parser parses your content as JSON not string, since both are syntactically the same (using the pipe symbol). Therefore, its difficult. In 1.0 you could disable validation for examples.

**Comment by sichvoge** [comment]
OK - updated to the newest version of api-workbench and it seems that the parser does not detect it as a warning anymore. cc/ @ddenisenko

**Comment by geosmart** [comment]
still have the error message : ‘Error string is expectedat line 59 col 17’
I upload the raml file in gist  [api.raml](https://gist.github.com/geosmart/df3cd88832c07117d775fc7510276713)

**Comment by sichvoge** [comment]
Yes, after updating workbench I am getting the same error. Its an issue on the parser that I have reported [here](https://github.com/raml-org/raml-js-parser-2/issues/421) already.

**Comment by geosmart** [comment]
OK, hope this can be fixed as soon as possible.

**Comment by sichvoge** [comment]
Yes, its critical issue so expect something asap.

**Comment by ddenisenko** [comment]
Looks to be fixed.
