### ISSUE TITLE
unknown type as an option of union type when declaring nullable string

### ISSUE THREAD

**Issue by JohnMcAvinue** [mulesoft/api-workbench#295]
I upgraded the api-workbench package yesterday to version 0.8.36 and now there are issues being reported where there were previously none, when I declare a property type as string or null. I'm doing it like this:

deviceName:
    description: Device Name
    type: string | null

It is reporting an issue on the type declaration and the error is:

"unknown type as an option of union type".

Any ideas how I can resolve this, or is this an issue with the latest version of workbench?

Thanks

**Comment by sichvoge** [comment]
Yes, there was a change in the spec for `null` being very YAML centric and YAML parser had their specific interpretation. Therefore, `null` has been changed to `nil`. See the specs [release notes](https://github.com/raml-org/raml-spec/releases/tag/1.0.1).

**Comment by JohnMcAvinue** [comment]
Yes that's it, thank you very much!
