### ISSUE TITLE
using colon in description cause error

### ISSUE THREAD

**Issue by e-cloud** [mulesoft/api-workbench#302]
![image](https://cloud.githubusercontent.com/assets/5255354/18349193/92f636f8-7602-11e6-832f-32e81bcdd409.png)

see the captured image

**Comment by KonstantinSviridov** [comment]
Hi, @e-cloud 

Most YAML parsers consider such code as invalid. You should enquote the value:
```
description: "(unit: m)"
```
or
```
description: '(unit: m)'
```

Regards, Konstantin

**Comment by e-cloud** [comment]
Yes, that is what i did for avoiding error. However, isn't it some kind of bug for the validator or parser?

**Comment by ddenisenko** [comment]
Well, that's the error that YAML parser reports. You can report it in the YAML parser repository here: https://github.com/mulesoft-labs/yaml-ast-parser , but I can say that YAML parser behavior looks reasonable.

**Comment by e-cloud** [comment]
looks like it's reasonable indeed for a reserved indicator. refer from here : http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210
