### ISSUE TITLE
why showing errors in DataType fragment file

### ISSUE THREAD

**Issue by e-cloud** [mulesoft/api-workbench#303]
![image](https://cloud.githubusercontent.com/assets/5255354/18349467/2b277d6e-7604-11e6-9b63-51190c2cd935.png)

As [the spec says](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#typed-fragments), except `Library, Overlay, and Extension`, other structures should stay as the specification which is what i did. 

However, it shows error.

**Comment by KonstantinSviridov** [comment]
Hi, @e-cloud 

A RAML fragment file can contain a single definition which is not placed under a key. You may check an  example of resource type fragment using the same link.

In your case there would be two fragments:
```
#%RAML 1.0 DtatType
type: object
properties: ...
```
and
```
#%RAML 1.0 DataType
description: some description
type: number
maximum: 2556115199
minimum: 946656000
```

Regardds, Konstantin

**Comment by e-cloud** [comment]
so, it that means my code should be declared as a library?

**Comment by ddenisenko** [comment]
Yes, if you wish to declare several types in a single file, library is a preferred method. Actually, it is a preferred method overall for declaring types for reuse.

**Comment by e-cloud** [comment]
However, there is a little shortage for a library. You have to use the namespace to refer the target type

**Comment by ddenisenko** [comment]
Well, you can always create a local shortcut by extending a local type from the library type:
```
types:
  MyLocalType: libNamespace.LibType
```

**Comment by e-cloud** [comment]
oooh, good, it's a better approach. Thanks anyway.
