### ISSUE TITLE
API Console post body text cursor issue

### ISSUE THREAD

**Issue by yamsellem** [mulesoft/api-workbench#304]
Hi,

The api console "body" textarea:
— has a cursor that always goes to the end on each keypress, so editing is very difficult
— do not handle copy pasting

Plus, it will be very cool to have the sample (if it exists) here, maybe the value already filled in, so clicking on post could be tested in a breath.

![cusror](https://cloud.githubusercontent.com/assets/606754/18477119/d80482f4-79cc-11e6-9bc9-58b309f908b5.png)

Thanks.

**Comment by ddenisenko** [comment]
>— has a cursor that always goes to the end on each keypress, so editing is very difficult
Reproduced, agree.

>— do not handle copy pasting
Works for me. Which OS do you use?

>Plus, it will be very cool to have the sample (if it exists) here, maybe the value already filled in, so clicking on post could be tested in a breath.

Agree.

TODO: split into a ticket per use case.

**Comment by dreamflyer** [comment]
will be published in v0.8.38.
