### ISSUE TITLE
API Console ignore {version} in baseUri

### ISSUE THREAD

**Issue by yamsellem** [mulesoft/api-workbench#307]
Using a raml fil with a {version} marker does not work (it is not ignored in the api console).

```
baseUri: http://localhost:8000/v{version}
```

**Comment by hadrienk** [comment]
+1

**Comment by ddenisenko** [comment]
![versioninuri](https://cloud.githubusercontent.com/assets/14824966/18574312/1d32e7be-7bf6-11e6-9b7f-dcac233ac7c8.png)

Do you mean that the version from RAML code is not automatically inserted into the form field?
Because I do see the version being ignored, and its does not look right for me.

**Comment by yamsellem** [comment]
Yep, I mean the version is not inserted, that's right ;-).

**Comment by dreamflyer** [comment]
will be published in v0.8.41.
