### ISSUE TITLE
Option to re-run validation

### ISSUE THREAD

**Issue by coltonlw** [mulesoft/api-workbench#313]
I am working with a RAML spec that uses !includes for each resource.  I find that I have to close my root api.raml file, quit atom, re-open atom, and then open api.raml every time I want the validation to re-run.  If there was a menu option to clear the jsonschema $ref cache and re-run validation, that would be spectacular

**Comment by ddenisenko** [comment]
Agree.

**Comment by ddenisenko** [comment]
Implemented, available from context menu, will be published in 0.8.40.

**Comment by coltonlw** [comment]
@ddenisenko Awesome!!!!!  Thanks for being so responsive
