### ISSUE TITLE
accuweather link is broken in popular apis

### ISSUE THREAD

**Issue by kyagen** [mulesoft/api-workbench#32]
This is actually the first one in the list so it's likely to be selected.

No idea which others. suggest creating a means to automate testing these if they might change/break unexpectedly.

**Comment by petrochenko-pavel-a** [comment]
Hi @kyagen, thanks for bringing it up. This is because `AccuWeather` does not have a production branch (only master) and production is an a default branch (you can configure it) we probably should create special branch for every API and then point Atom to use it.

Regards,
Pavel

**Comment by aldonline** [comment]
@sichvoge This is more of a UX issue than it is technical. It requires some product management thinking ( Starting from: Who and why? )

**Comment by VasiliyLysokobylko** [comment]
Fixed. Fix should be available in 0.8.7.

Now list contains only repos with `production` branch.
