### ISSUE TITLE
The following line to an example has no suggestions

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#327]
Duplicate of https://github.com/mulesoft/raml-suggestions/issues/13.

When there is an example node, inside of a type or a response, the following line does not have any suggestions, but it should. In the case that the caret in two lines below the example it works fine.
This is the case that doesn't work:
![screen shot 2016-10-06 at 5 57 32 pm](https://cloud.githubusercontent.com/assets/5315281/19170367/7dea96da-8bee-11e6-9c1f-885f44e11114.png)

This are the suggestions it should provide:
![screen shot 2016-10-06 at 5 57 55 pm](https://cloud.githubusercontent.com/assets/5315281/19170374/82e1d194-8bee-11e6-9a76-dd96c76bcaea.png)

**Comment by dreamflyer** [comment]
will be published in v0.8.39.
