### ISSUE TITLE
It suggests options for a node that already have a node

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#328]
Duplicate of https://github.com/mulesoft/raml-suggestions/issues/14

I've notice when there is a node with a value and a new value is suggested, the result of adding this suggested value is an invalid.

Here it happened in in protocols (Here more protocols can be added as a list, but is not the suggested case):
<img width="292" alt="screen shot 2016-10-07 at 4 39 12 pm" src="https://cloud.githubusercontent.com/assets/5315281/19203274/c12cb252-8cac-11e6-9759-029cf8453019.png">

Here with a type inside a response:
<img width="420" alt="screen shot 2016-10-07 at 4 39 40 pm" src="https://cloud.githubusercontent.com/assets/5315281/19203281/c909e6f2-8cac-11e6-803e-7f81e3f59685.png">

**Comment by dreamflyer** [comment]
will be published in v0.8.39
