### ISSUE TITLE
Details tab inoperative with RAML 1.0 files

### ISSUE THREAD

**Issue by stonehippo** [mulesoft/api-workbench#338]
API Workbench Version: 0.8.39
OS: Mac OS X 10.11.6
Atom: 1.11.2

When working with RAML 1.0, the Details panel does not show any content. RAML 0.8 definitions work as expected, with palette, etc.

Steps to Reproduce:
1. Start API Workbench
2. Open RAML 1.0 file
3. Select an element in the API description and inspect it with the Details tab - not details appear
4. Switch the RAML declaration to 0.8 - Details appear
5. Switch the RAML declaration to 1.0 -Details disappear
![screen shot 10-28-2016 at 8 43 57 am](https://cloud.githubusercontent.com/assets/43452/19806736/b43e44d6-9cea-11e6-9cea-6e13ca4d0a82.png)
![screen shot 10-28-2016 at 8 44 05 am](https://cloud.githubusercontent.com/assets/43452/19806734/b43cdcfe-9cea-11e6-9a30-a4e8ab41522d.png)

**Comment by stonehippo** [comment]
This appears to be a local install issue. I was able to get the details tab to work on another Mac, with macOS 10.12 installed, to work just fine.

**Comment by stonehippo** [comment]
Reopening, as the details tabs seems to be unstable with RAML 1.0 files.

If I have an atom instance where api-workbench (and the linter dependency) are the only packages installed, the Details tabs works fine for RAML 1.0 and 0.8 files. Occasionally, the Details tab will stop working after other packages are installed. There's not clear pattern for any given package causing the problem: I've had it happen after installing `autocomplete-clang` or `build`. And the first time it happened was install `api-workbench` as the most recent package.

Overall, it seems like there's a bug in the Details tab.

**Comment by ddenisenko** [comment]
You also do not have any coloring in the RAML editor. Do you have code completion, context menu?

Does it help to restart Atom?
All in all, we need a way to reproduce before we can proceed to fixing this one, if it is caused by API Workbench.

**Comment by stonehippo** [comment]
@ddenisenko:

Restarting Atom doesn't resolve the issue. Code completion and the context menu are also unaffected. And the issue on pertains to RAML 1.0 files. Simply switching the RAML declaration to `#%RAML 0.8` restores the Details panel; going back to 1.0 removes it again. I have been able to resolve the issue by removing my `~/.atom` directory and starting fresh. However, at random points (including applying the latest update of the API-Workbench), the details panel fails.

The lack of syntax highlighting on the RAML file seems to be an different issue. It only occurs when Atom restarts and reloads the previously loaded doc. Closing and opening the file again restores the colors and syntax highlighting.

The implication is that there's an issue at times parsing RAML 1.0 files. I haven't dug deeply into how the Details panel is driven, but given it's context-awareness, I'm assuming that the RAML file is parsed in realtime.

**Comment by ddenisenko** [comment]
Could you please attach on details failure: 
1) Whole RAML project (basically, all files/folders you see in Atom). 
2) your `~/.atom` folder

I'll try reproducing locally.

**Comment by stonehippo** [comment]
@ddenisenko:

Here you go. The .atom is too large to send via GitHub, so I've put it up on Dropbox. If you need anything else, let me know.


[~/.atom directory](https://dl.dropboxusercontent.com/u/92549/dot_atom.tar.gz)
[raml_example.tar.gz](https://github.com/mulesoft/api-workbench/files/578472/raml_example.tar.gz)

**Comment by dreamflyer** [comment]
will be published in v0.8.41.
