### ISSUE TITLE
!include with absolute paths should be from root document

### ISSUE THREAD

**Issue by rawkode** [mulesoft/api-workbench#351]
When including other RAML files, typing `/` provides us with auto-complete from the root of our filesystem, rather than from the root document, as stated in the RAML spec.

I understand this may be because API Workbench can't determine what the root document is, perhaps? Can we maybe set this in a config file?

Screenshot attached:
![rootwrong](https://cloud.githubusercontent.com/assets/145816/20246255/1a6cfece-a9ab-11e6-9cd9-5913a3715e6b.png)

**Comment by rawkode** [comment]
If this is user error, I'd appreciate some advice :smile:

**Comment by sichvoge** [comment]
I don't think it is ;) I think that's the parser that resolves it from the root of your filesystem. @ddenisenko is that right? do we always resolve from the root, or should we consider to use the project root for that? any concerns on that?

**Comment by ddenisenko** [comment]
Yes, completion and parser looks to be handling absolute local paths not as the spec states, which is a bug:

`A path that begins with a single slash ("/") and is interpreted relative to the root RAML file location.`

Honestly, I would either forbid using absolute local paths in includes (better) or resolve them against FS root (worse). What spec states looks strange for me, basically, the spec invents "root RAML file" definition, which is nowhere defined and is as dangerous as calculating from FS root, but for other reasons: the behaviour of absolute paths inside libraries, extensions, fragments all of a sudden starts changing depending on which file was specified first in the list of load method arguments.

**Comment by rawkode** [comment]
> spec invents "root RAML file" definition

True, this is a magical value, but absolute paths from this root feel nicer than polluting my RAML files with lots of relative paths.

Can we make this config?

**Comment by sichvoge** [comment]
How do you think that config should look like? Guess we could have something as `option` that lets you define the root path. Is it that what you want?

**Comment by rawkode** [comment]
Based on some other projects I've seen, it's somewhat common to define a comma-separated list of values that the plugin would loop through for validity.

```json
root_raml_documents = [ "main.raml", "api.raml" ]
```
