### ISSUE TITLE
Atom slows down after a while of editing

### ISSUE THREAD

**Issue by LairdTurner** [mulesoft/api-workbench#357]
Hello!

I'm currently using Atom 1.12.5 and the newest version api-workbench.
After a while of editing raml files atom slows down rapidly. After a while the whole program
responds very, very slowly, so I must close the program, if it's still possible and have to restart Atom.

regards

        -René

**Comment by sichvoge** [comment]
That might be a memory leak that we investigate at the moment. Please follow #2 for further information. If you don't mind I would close this issue has its a duplicate for that as well.

**Comment by ddenisenko** [comment]
Thanks for reporting. Please track the following ticket: https://github.com/mulesoft/api-workbench/issues/2
