### ISSUE TITLE
API-Console does now show the progress of the request

### ISSUE THREAD

**Issue by jcenturion** [mulesoft/api-workbench#37]
I would like to have at least a loading indicator in order to know that the `API-Console` is making a request.

![api-console-wb](https://cloud.githubusercontent.com/assets/302314/10972449/07604e5e-83b8-11e5-84d4-edf3e0a8f91d.gif)

**Comment by blakeembrey** [comment]
There is not HTTP request being made, you're reading RAML documentation. Is there something that happened that made you think it was doing a HTTP request.
