### ISSUE TITLE
Extract resource type action works once

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#375]
Duplicating https://github.com/mulesoft-labs/api-workbench/issues/2670

Clone Uber spec from a popular APIs.
Open api.raml -> Set cursor at the any resource -> Extract resource type with all methods -> Extract any resource type again
### Result:

IDE creates only first resource type.
Second resource type is lost.

**Comment by dreamflyer** [comment]
will be published in v0.8.43.
