### ISSUE TITLE
Deprecated selector in `api-workbench/styles/raml-general.less`

### ISSUE THREAD

**Issue by DataGreed** [mulesoft/api-workbench#384]
In `api-workbench/styles/raml-general.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .gutter .line-number.ramlscript .icon-right,
atom-text-editor::shadow .gutter .line-number.ramlscript .icon-right` => `atom-text-editor .gutter .line-number.ramlscript .icon-right,
atom-text-editor.editor .gutter .line-number.ramlscript .icon-right`

* `atom-text-editor .gutter .line-number.ramlscript .icon-right:before,
atom-text-editor::shadow .gutter .line-number.ramlscript .icon-right:before` => `atom-text-editor .gutter .line-number.ramlscript .icon-right:before,
atom-text-editor.editor .gutter .line-number.ramlscript .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by dreamflyer** [comment]
will be published in v0.8.43.
