### ISSUE TITLE
Deprecated selector in `api-workbench/styles/raml-overlay.less`

### ISSUE THREAD

**Issue by DataGreed** [mulesoft/api-workbench#385]
In `api-workbench/styles/raml-overlay.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ddenisenko** [comment]
Thanks for info.

Are there any details to read regarding this change:

```Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary.``` ?

**Comment by ridouta** [comment]
Same issue here with v1.13.0 Atom.  Can't create a workbench project

**Comment by DataGreed** [comment]
@ddenisenko seems the guide to migration is here - https://github.com/atom/flight-manual.atom.io/blob/7d0d8b9213472ef054b3628f6b104b402a57e598/content/shadow-dom/sections/removing-shadow-dom-styles.md

**Comment by ddenisenko** [comment]
Thanks, @DataGreed

**Comment by DataGreed** [comment]
Не за что :)

**Comment by dreamflyer** [comment]
will be published in v0.8.43.
