### ISSUE TITLE
Unable to edit new RAML project directory and details in Atom 1.13

### ISSUE THREAD

**Issue by DataGreed** [mulesoft/api-workbench#386]
Whan creating a new RAML project in atom 1.13 you cannot specify directory and other project details (the fields are non-editable). 

I tried to edit this fields in DOM inspector, though the project was still created in my homedire with default name

**Comment by DataGreed** [comment]
I've temporarily downgraded to atom 1.12.9 as a workaround

**Comment by dreamflyer** [comment]
will be published in v0.8.42.
