### ISSUE TITLE
MediaType in the root doesn't work

### ISSUE THREAD

**Issue by deepshadow** [mulesoft/api-workbench#396]
I used mediaType: application/json in the root, however, all post methods do not send data with content type **application/json.** 
POSTMAN and other tools are send these requests successfully. 

To reproduce try to:
1. Create resourceTypes
2. Create Type
3. Create Traits
4. include them in the root with used mediaTypes.
5. Generate API console and send POST request.
6. Check logs of your service where you will see that API workbench API console sends request without content type.

**Comment by dreamflyer** [comment]
will be published in v0.8.43.
