### ISSUE TITLE
Possibly incorrect discriminator subtype warning.

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft/api-workbench#399]
I'm getting what looks to be an incorrect warning in my specification.  Suppose I define

    types:
      Error:
        discriminator: type
        properties:
          type:
            type: string
          ...

        example:
          type: internal_server_error
          ...

      ServerError:
        type: Error
        discriminatorValue: internal_server_error

The example generates the warning 

> None of the 'Error' type known subtypes declare 'internal_server_error' as value of discriminating property 'type'

But that doesn't seem true, as ServerError has this value.  Am I missing something here, or is the warning being generated incorrectly?

Thanks

**Comment by joaocarreiras** [comment]
Hi,

In api-workbench 0.8.43 on Windows 10 I still get this error when I "Extract Library" as per the example provided in http://apiworkbench.com/docs/, section "Extracting Library". I've checked the source code and raml-1-parser version is 1.1.14 and I checked the code snippet referenced by ddenisenko in raml-org/raml-typesystem@2dd1212 and it's the same.
I've just installed this package today. 

RAML files
#%RAML 1.0
title: Pet Shop

version: v1
baseUri: /petshop
mediaType:
  - application/json
protocols:
  - HTTP
description: API example designed with API Workbench
**uses:
  NewLibrary: NewLibrary.raml**
types:
  Mammal:
    type: NewLibrary.Pet
  Bird:
    type: NewLibrary.Pet
    properties:
      wingLength: number

resourceTypes:
/pets:
  type:  { NewLibrary.CollectioNewLibrary.Pet{item : Pet} }
  /{id}:
    type:  { NewLibrary.MembeNewLibrary.Pet{item : Pet} }
  get:
    queryParameters:
      petKind:
        enum:
          - bird
          - mammal
    is: [NewLibrary.FilterableByPrice]
/birds:
  type: { NewLibrary.Collection: {item: Bird} }
  get:
    is: NewLibrary.FilterableByPrice
  /{id}:
    type: { NewLibrary.Member: {item : Bird} }

/mammals:
  type: { NewLibrary.Collection: {item: Mammal} }
  get:
    is: NewLibrary.FilterableByPrice
  /{id}:
    type: { NewLibrary.Member: {item : Mammal} }

The referenced Library
#%RAML 1.0 Library
types:
  Pet:
    discriminator: kind
    properties:
      name: string
      kind: string
      price: number
      color:
        enum:
          - White
          - Black
          - Colored
    example:
      name: "Snoopy"
      kind: "Mammal"
      price: 100
      color: Black
resourceTypes:
  Collection:
    post:
      body:
        application/json:
          type: <<item>>
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
  Member:
    delete:
      responses:
        204:
    put:
      body:
        application/json:
          type: <<item>>
traits:
  FilterableByPrice:
    queryParameters:
      priceLessThan:
        type: number
      priceMoreThan:
        type: number


Thanks in advance,
João C.
