### ISSUE TITLE
Applying multiple transformation functions

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft/api-workbench#401]
I'm not sure if this is a problem in the API workbench, the specification, or my misunderstanding.  But if I try to apply multiple transformation functions, such as
    
    description: Test <<resourcePathName|!singularize|!uppercamelcase>>
then the description is ignored.  If I apply just one of them it works.  Are multiple transformations supposed to be allowed?  And if so, is this a bug, or am I using the wrong syntax to apply them?

**Comment by sichvoge** [comment]
Seems that should have been fixed with https://github.com/raml-org/raml-js-parser-2/issues/446. You are welcome to open the issue again.

**Comment by KonstantinSviridov** [comment]
Hi, @KevinMitchell 

Actually, you are using the correct chaining style. But we can not reproduce your issue in the current API Workbench release.

![fchain](https://cloud.githubusercontent.com/assets/6206034/22434152/84ea848a-e74d-11e6-9ed6-db024a0b1307.png)


Could you, plaese, attach an example raml and describe the way to see that the chaining does not actually work.

Regards, Konstantin

**Comment by KevinMitchell** [comment]
OK, I'm probably running an older version than I was expecting then.  I'll do some digging.  Thanks for your help,

Kevin
