### ISSUE TITLE
Uncaught TypeError: llch.asMapping is not a function

### ISSUE THREAD

**Issue by joaocarreiras** [mulesoft/api-workbench#412]
[Enter steps to reproduce:]

1. From http://apiworkbench.com/docs/, I've this RAML
#%RAML 1.0
traits:
  FilterableByPrice:
    queryParameters:
      priceLessThan:
        type: number
      priceMoreThan:
        type: number
title: Pet Shop
version: v1
baseUri: /petshop
mediaType:
  - application/json
protocols:
  - HTTP
description: API example designed with API Workbench
types:
  Pet:
    properties:
      name: string
      kind: string
      price: number
    example:
      name: "Snoopy"
      kind: "Mammal"
      price: 100
  Mammal:
    type: Pet
    properties:
      color:
        enum: [White, Black, Colored]
  Bird:
    type: Pet
    properties:
      wingLength: number

resourceTypes:
  Collection:
    post:
      body:
        application/json:
          type: <<item>>
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
  Member:
    delete:
      responses:
        204:
    put:
      body:
        application/json:
          type: <<item>>
/pets:
  type:  { Collection: {item : Pet} }
  /{id}:
    type:  { Member: {item : Pet} }
  get:
    queryParameters:
      petKind:
        enum:
          - bird
          - mammal
    is: [FilterableByPrice]

2. "Pull Up" Mammal type.

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.43

### Stack Trace

Uncaught TypeError: llch.asMapping is not a function

```
At C:\Users\joao.carreiras\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\mutators.js:102

TypeError: llch.asMapping is not a function
    at findInsertionPoint (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/mutators.js:102:30)
    at Object.addToNode (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/mutators.js:384:26)
    at ASTNodeImpl.add (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1452:18)
    at e.t.mergeNode (/packages/api-workbench/main.js:4:743)
    at /packages/api-workbench/main.js:4:341
    at Array.forEach (native)
    at e.t.mergeTrees (/packages/api-workbench/main.js:4:319)
    at e.performOk (/packages/api-workbench/main.js:4:12745)
    at /packages/api-workbench/main.js:3:31903
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:414:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:414:31)
```

### Commands

```
     -1:00.1.0 core:cut (input.hidden-input)
  3x -0:59.4.0 core:backspace (input.hidden-input)
     -0:57.1.0 core:paste (input.hidden-input)
  3x -0:54.2.0 core:backspace (input.hidden-input)
     -0:51 snippets:next-tab-stop (input.hidden-input)
     -0:51 snippets:expand (input.hidden-input)
     -0:51 editor:indent (input.hidden-input)
  4x -0:49.8.0 core:backspace (input.hidden-input)
     -0:42.4.0 snippets:previous-tab-stop (input.hidden-input)
     -0:42.4.0 editor:outdent-selected-rows (input.hidden-input)
     -0:39.2.0 snippets:previous-tab-stop (input.hidden-input)
     -0:39.2.0 editor:outdent-selected-rows (input.hidden-input)
     -0:37.8.0 snippets:previous-tab-stop (input.hidden-input)
     -0:37.8.0 editor:outdent-selected-rows (input.hidden-input)
     -0:35.5.0 snippets:previous-tab-stop (input.hidden-input)
     -0:35.5.0 editor:outdent-selected-rows (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
linter 1.11.23 
```

**Comment by dreamflyer** [comment]
will be published in v0.8.44.
