### ISSUE TITLE
Checkboxes don't show

### ISSUE THREAD

**Issue by ledj0304** [mulesoft/api-workbench#444]
Hello,

I am new to RAML and to the API workbench. While kicking the tires, I tried to create a new API spec using the tools provided in the workbench.

From the "Create new Project" to "Create resources" etc, there are no checkboxes showned in any windows. I can clearly see the text (ex: in Creating new resources: get : get request transfer... but, when comparing with the Atom documentation, a can see that there are no checkboxes displayed on the left of th method.  

Refer to the attached screen capture for 

I work on Ubuntu 16.04.

Thanks

Jacques

![atom-api workbench no checkboxes](https://cloud.githubusercontent.com/assets/6115545/24358830/6dac0cb8-12d0-11e7-8e9e-a59e3333b71d.png)

**Comment by dreamflyer** [comment]
will be published in v0.8.45.

**Comment by ledj0304** [comment]
Now this is fast. Thanks for the great support.
