### ISSUE TITLE
Release based on branch api-workbench-server

### ISSUE THREAD

**Issue by dyeray** [mulesoft/api-workbench#445]
I am very happy to hear there is a branch that tries to improve performance. Will this be released on apm at some point? Are there any instructions to get it working right now for the less familiar with the platform?

I use this plugin on my workplace and I am currently getting very poor performance (almost unusable) with ~1000 line file and this looks promising.

**Comment by ddenisenko** [comment]
Please see https://github.com/mulesoft/api-workbench/issues/464 , the prototype is published. The beta version as binary for Atom repository and VS Code client will be published later in a few weeks. The prototype will be updated along the course.

**Comment by dyeray** [comment]
Thanks, I'll give it a try.
