### ISSUE TITLE
W7 Atom installation error

### ISSUE THREAD

**Issue by matteox** [mulesoft/api-workbench#45]
Installing “api-workbench@0.8.6” failed.Hide output…

npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Dev\\AppData\\Local\\atom\\app-0.201.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Dev\\AppData\\Local\\atom\\app-0.201.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Dev\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Dev\\.atom\\.apmrc" "install" "C:\\Users\\Dev\\AppData\\Local\\Temp\\d-115108-5320-hzgkn1\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file C:\Users\Dev\.atom\.apm\es6-weak-map\0.1.4\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 
npm ERR! File: C:\Users\Dev\.atom\.apm\es6-weak-map\0.1.4\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by ddenisenko** [comment]
@matteox , thank you for letting us know.

While we trying to reproduce the case, could you please let us know if you got this error on a fresh Atom installation, or you already had Atom installed before.

**Comment by sichvoge** [comment]
Removing the priority for now. We will prioritise it again if that is going to be a re-produceable error.

**Comment by matteox** [comment]
Hi sichvoge,

I got this error with a previously installed Atom instance.  I uninstalled Atom and tried again - same error.

**Comment by sichvoge** [comment]
@ddenisenko could you try again. seems a windows issue, but haven't seen the package that is issuing the problem in our package.json.

**Comment by matteox** [comment]
Success.  0.8.6 installed on W7.  Thanks for your involvement.

**Comment by sichvoge** [comment]
cool - closing it then. thanks @matteox for raising it
