### ISSUE TITLE
Update tutorial

### ISSUE THREAD

**Issue by ericzon** [mulesoft/api-workbench#450]
First of all, thanks for this nice tutorial: http://apiworkbench.com/docs/
I'm learning raml so maybe I'm wrong, but I've just followed all the steps perfectly until section  "Extracting the library".  The generated files doesn't follow exactly the same syntax of the tutorial and raise some linter warnings: 

On main api file, including NewLibrary throws this error:
[img1](http://i.imgur.com/fyppqSl.png)

On NewLibrary.raml generated appears this other:
[img2](http://i.imgur.com/fd1Aebs.png)

It would be great to fix / update that section.

I attach [here](https://gist.github.com/ericzon/401781bbd216ec808065137de43ad4a2) both files.

**Comment by dreamflyer** [comment]
separate https://github.com/raml-org/raml-js-parser-2/issues/759 issue created.

All other issues in tutorial are fixed.
