### ISSUE TITLE
Mocking in the API Workbench

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft/api-workbench#454]
Hi,  
I'm a bit confused about what the "Make an API Request" button is supposed to do in the API Console view.  Reading the blog article https://blogs.mulesoft.com/dev/api-dev/ramling-again-with-api-workbench-from-setup-to-design/ it sounds like the console can mock the calls, which is what I was hoping for.  However, when I click the button to make a request it looks like its trying to make a real call, as it complains that it can't connect to the URI.  So does the workbench support mocking, or just a "try me" to a real service, or both?  And if it's just a mocking service then why is it complaining about not being able to connect?

Thanks,
Kevin

**Comment by ddenisenko** [comment]
There is no mocking service currently in API Workbench, pressing the "Make an API Request" button does perform the actual API request to the real server. 

There is another instance of console in development, which has mocking service, and which may be integrated into API Workbench in future.

**Comment by KevinMitchell** [comment]
Thanks for the clarification.  So it sounds like the best approach for now is to deploy an external mocking service and then set the baseUri to point to that.  Thanks.
