### ISSUE TITLE
Make API Request with Security Scheme

### ISSUE THREAD

**Issue by scotchneat** [mulesoft/api-workbench#455]
I have an api configured with a [Security Scheme](https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#security). In this case, we're using headers to pass tokens to the api. However, when I test the 'Make API Request' through the API Console, I see the scheme options in a drop down, but I'm not able to specify a value for the given scheme. Without the value, all requests will fail.

Am I missing something? 
Is it possible to provide a value that can be sent in the specified header?

**Comment by dreamflyer** [comment]
will be published in v0.8.45.
