### ISSUE TITLE
In the Create RAML Project wizard "Use RAML 1.0 Draft" should be checked by default

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#47]
Otherwise our users experience 0.8 by default.

**Comment by usarid** [comment]
And it's not draft, let's just call it RAML 1.0 without any qualifiers.






On Wed, Nov 11, 2015 at 6:58 PM -0800, "Denis Denisenko" <notifications@github.com> wrote:












Otherwise our users experience 0.8 by default.

**Comment by sichvoge** [comment]
We should start by renaming `RAM 1.0 Draft` to `RAML 1.0`

**Comment by ddenisenko** [comment]
Fixed. Fix will be available in 0.8.7.
