### ISSUE TITLE
Unreadable font color 

### ISSUE THREAD

**Issue by ledj0304** [mulesoft/api-workbench#481]
Hello,

I use Ubuntu 16.04 and have installed api-workbench 0.8.44

The black background does not allow me to read some fint colors namely the RAML 1.0 line wich is (to my best guess) a very dark green. I did not find anywhere to change that particular font color or to lighten the editor background. 

My screen brilliance is dimmed and color temperatur lowered (redshift) because it hurts my eyes on the long run. I like the dark background but need to have contrasting colors for the content. Either a change the font (for which there are no clear documentation eg which css class to change) or change the background to some shade of grey. This is a basic usability concern otherwise, I love the tool.

![image](https://cloud.githubusercontent.com/assets/6115545/25860560/e403ddae-34af-11e7-8d34-5cee777174fc.png)

This image was taken with full brilliance up. COuld you let us know how to change this background color please.

THanks,

Jacques

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
