### ISSUE TITLE
Empty RAML Editors Tools Pane (details)

### ISSUE THREAD

**Issue by ronaldbijker** [mulesoft/api-workbench#521]
I'm new to API Workbench so I decided to follow this instruction: http://apiworkbench.com/docs/. The details pane should contain useful actions that change depending on the context inside the RAML editor (http://apiworkbench.com/docs/#adding-resource-and-methods). In my case the Details pane (activated by picking Open RAML Editor Tools) is completely blank:

![image](https://user-images.githubusercontent.com/21905347/36724992-2ad43dea-1bb5-11e8-903b-4c33ea8bb36b.png)

Atom version: 1.24.0
api-workbench 0.8.47

**Comment by gui1207** [comment]
Hi, 

Same problem here. It's started after atom update 1.24.0.

As a workaround i've downgraded to atom 1.23.3.

**Comment by hirsts** [comment]
I can confirm that using 1.23.3 also fixed the issue for me

**Comment by ddenisenko** [comment]
Thanks, we'll investigate and fix it.

**Comment by ddenisenko** [comment]
Should be fixed in 0.8.48.
