### ISSUE TITLE
Not seeing linter errors

### ISSUE THREAD

**Issue by matthewnauman** [mulesoft/api-workbench#547]
Ive done a fresh install of Atom, and the api-workbench package.  More specifically here is a complete package list of what i have installed:
![screenshot from 2019-02-22 10-29-38](https://user-images.githubusercontent.com/43712077/53252416-d1853480-368c-11e9-990c-47e62247396b.png)
I created a new RAML project with a simple error which you can see in the "Details" section to the right, but it does not show up in the linter task bar in the bottom-left, neither am i seeing the highlighting in my document i would expect from linter/linter-ui.  
![screenshot from 2019-02-22 10-44-22](https://user-images.githubusercontent.com/43712077/53253296-dfd45000-368e-11e9-96c8-7c7f45fc16d1.png)
Linter: Debug for the file yields the following:
![screenshot from 2019-02-22 10-47-49](https://user-images.githubusercontent.com/43712077/53253462-56714d80-368f-11e9-9461-2ca6f2e25917.png)
(Running on CentOS Linux release 7.5.1804)
Any assistance would be appreciated.

**Comment by ageoghegan** [comment]
I've seen this issue.  When I looked into it the linter version 2.3 has some breaking changes that break the RAML parser.  It hasn't been updated to cope with the linter 2.x features.  If you downgrade the linter version to 2.0 it seems to start working again.

**Comment by matthewnauman** [comment]
Thanks, downgrading linter did the trick.
