### ISSUE TITLE
Suggested content-type should be multipart/form-data instead of multipart/formdata

### ISSUE THREAD

**Issue by boukeversteegh** [mulesoft/api-workbench#76]
Wasted more than an hour wondering why the browser api-console crashed. The Atom api-console package generates suggestions for content-types, and one of them is broken.

``multipart/formdata`` (incorrect)
``multipart/form-data`` (correct)

In api-console.js it is seen that the contentType is checked against FORM_DATA (``multipart/form-data``), this never matches when you follow the UI suggested content types.

![image](https://cloud.githubusercontent.com/assets/53926/11850351/0c5e2940-a42d-11e5-975c-63336d03ed02.png)

I have also created an issue on the api-console package, as i wasn't sure where to post this.

**Comment by ddenisenko** [comment]
Clearly a bug.

**Comment by ddenisenko** [comment]
Fix should be available in 0.8.12.
