### ISSUE TITLE
Don't require "title" property on included RAML files

### ISSUE THREAD

**Issue by odissea** [mulesoft/api-workbench#79]
Hi, I have extracted a few types/resourceTypes to extra .raml files in a little subdirectory structure. API Workbench now triggers issues such as:
```
Error Unknown node: properties at line 1 col 1
Error Missing required property title at line 1 col 1
```

Should I rename those files to a different extension, or is it possible to implement a setting in api-workbench to ignore these full validations on partial files?

**Comment by sichvoge** [comment]
Can you post your fragment?

**Comment by ddenisenko** [comment]
@odissea please post your fragment, or at least let us know, which comment your fragment starts with.

**Comment by odissea** [comment]
Example:
```RAML
#%RAML 1.0
title: Example API
version: v1
baseUri: http://api.example.com/{version}/
mediaType: application/json
types:
    Page: !include types/page.raml
/pages:
    /{id}:
        uriParameters:
            id:
                type: integer
        get:
            displayName: Used to retrieve a specific page
            responses:
                200:
                    displayName: Page returned successfully
                    body:
                        type: Page
                404:
                    displayName: Page not found
```

Now, opening types/page.raml looks, obviously, like this:
![image](https://cloud.githubusercontent.com/assets/3694614/11895362/605526fa-a57e-11e5-9fbe-ab69d48943cd.png)

The RAML 1.0 Spec gives a little example, that this should work:
http://docs.raml.org/specs/1.0/#raml-10-spec-typed-fragments

**Comment by ddenisenko** [comment]
`#%RAML 1.0` comment declares API. Your typed fragments declares a type.

Here is the quotation from the spec:
```
A file to be included MAY begin with a RAML fragment identifier line, which consists of the text #%RAML followed by a single space followed by the text 1.0, followed by a single space followed by one of the following fragment identifiers:
```

Thus, you need to use `#%RAML 1.0 DataType` fragment in this case.

Due to a bug, shortcut syntax with avoiding "type" statement for object types will be not recognized in typed fragment, but using the full syntax of:
```RAML
#%RAML 1.0 DataType
type: object
properties:
  title: string
  description: string
```
is going to help.

**Comment by odissea** [comment]
Ahh, I somehow must have overlooked this in the spec.
Thank you very much @ddenisenko !

I will close this issue, sorry.
