### ISSUE TITLE
How to use ld+json for example output and be able to specify collections

### ISSUE THREAD

**Issue by redndahead** [mulesoft/api-workbench#80]
I'm sure the title doesn't do my question justice, but here is my situation. Given this main raml file:

````
#%RAML 1.0
---
title: Super API
baseUri: http://api.example.com
version: v1
mediaType: application/ld+json
uses:
  Endpoint: !include libraries/types/endpoint/endpoint.raml

/endpoint:
  get:
    description: Get a list of all items
    responses:
      200:
        body:
          application/ld+json:
            type: Endpoint.Items
            example: |
              {
                "@context": {
                  "hydra": "http://www.w3.org/ns/hydra/core#",
                  "gsb": "http://api.example.com/endpoint#",
                  "dc": "http://purl.org/dc/terms/",
                  "member": "hydra:member",
                  "id": "company:code",
                  "name": "dc:description"
                },
                "@type": "hydra:Collection",
                "@id": "http://api.example.com/endpoint",
                "member": [
                  {
                    "@id": "http://api.example.com/endpoint/1233",
                    "@type": "company:Endpoint",
                    "id": "1233",
                    "name": "Name 1"
                  },
                  {
                    "@id": "http://api.example.com/endpoint/1234",
                    "@type": "company:Endpoint",
                    "id": "1234",
                    "name": "Name 2"
                  }
                ]
              }
````

And this libraries/types/endpoint/endpoint.raml

````
  #%RAML 1.0 Library

types:
  Base:
    type: object
    properties:
      id: string
      name: string
    example:
      id: 1233
      name: Name 1
  Items:
    type: Base[]
    minItems: 1
    uniqueItems: true
````

I get these errors in api workbench for the main raml file. It seems to stem from the example.

> Required property:id is missed at line 20 col 13
> Required property:name is missed at line 20 col 13
> Unknown property:@context at line 20 col 13
> Unknown property:@type at line 20 col 13
> Unknown property:@id at line 20 col 13
> Unknown property:member at line 20 col 13

Any ideas on the best way to get the types and example to match up?

**Comment by sichvoge** [comment]
The example validation is always against a type definition. The validator does not recognise the properties defined, that includes `@context`, `@type`, `@id`, and the other as JSON+LD specific properties and therefore validates all of them against the properties defined in type `Endpoint.Items`. 

That is purely what the validator does - you define a type and the example will be validated against it property by property.

**Comment by sichvoge** [comment]
For what purpose do you want to define your types btw?

**Comment by redndahead** [comment]
So I define a type file as the description of an "object" (person, product, book, etc.). The way I define my types are the different ways the "object" is displayed. 
Base = minimum number of elements. These are usually seen in collections
Full = Full display of an object. Usually details.

Ok I understand that you need to define each property. But then how am I supposed to define a type that has multiple properties where one of them is a collection like Items?

**Comment by redndahead** [comment]
Ok I think I figured it out. Only thing I think I'm not able to do is being able to set minItems or uniqueItems values for the member array. Not a big deal to me, but if true then it maybe shows a limitation of the spec.

````
  #%RAML 1.0 Library

types:
  Base:
    type: object
    properties:
      "@id": string
      "@type": string
      id: string
      name: string
    example:
      id: 1233
      name: Name 1
  Items:
    "@context": object
    "@id": string
    "@type": string
    member: Base[]
````

**Comment by sichvoge** [comment]
Do you mean something like that?

```yaml
types:
  Base:
    type: object
    properties:
      "@id":
        type: string
        required: false
      "@type":
        type: string
        required: false
      id: string
      name: string
    example:
      id: 1233
      name: Name 1
  Items:
    properties:
      "@context": object
      "@id": string
      "@type": string
      member:
        type: Base[]
        minItems: 1
        uniqueItems: true
```

**Comment by redndahead** [comment]
That's it exactly. Thank you for the help.
