### ISSUE TITLE
Console not functioning in 0.8.10

### ISSUE THREAD

**Issue by fredericBregier** [mulesoft/api-workbench#82]
Today I had an update using APM.
With my current project, opening the API Console is not anymore fully fonctionnal.

The console opened, showing the very first resource, but almost all clickable elements are not functionnal:

 - View 1 more resource
 - GET or whatever command

Only clicking on resource change the position in the RAML editor. Nothing else.

Before I was able to see more.

Here is a simple raml file where I can reproduce the issue;

    #%RAML 1.0
    title: My test
    version: v1
    protocols: HTTP
    baseUri: http://mytest

    /helloworld:
      get:
        responses:
          200:
            body:
              application/json:
                type: object
                example: |
                  { "test" : "test" }
      /{id}:
        get:
          responses:
            200:
              body:
                application/json:
                  type: object
                  example: |
                    { "test" : "test" }

**Comment by ddenisenko** [comment]
Thank you for reporting this bug. 0.8.11 build with the fix is pushed. Please restart Atom after update.

**Comment by fredericBregier** [comment]
Well done! Thanks!
