### ISSUE TITLE
Error when using inline type definition on body

### ISSUE THREAD

**Issue by uudashr** [mulesoft/api-workbench#88]
The lint error "property body can not have scalar value"
```raml
mediaType: application/json
...
/user/location:
  post:
    body: Location
```

**Comment by beno** [comment]
seconded.

**Comment by ddenisenko** [comment]
@beno Please let me know in which particular case it does not work for you. This ticket looks like a leftover, which is already fixed.

**Comment by beno** [comment]
Never mind, I forgot to include a default media type. Perhaps the error message could be a bit more explicit.
