### ISSUE TITLE
Atom API Workench Console Not Showing Response Body ( 2 )

### ISSUE THREAD

**Issue by deividaspetraitis** [mulesoft/api-workbench#98]
Related to: #90 

Can't expand response body, it looks like this every time when response is larger than simple for example `{  'id' : 1 }` :

![capture2](https://cloud.githubusercontent.com/assets/5105752/12295285/d8c89f24-ba08-11e5-9d6a-b1cac6d3f195.PNG)

Please see GIF below:

![imageedit_1_4101969528](https://cloud.githubusercontent.com/assets/5105752/12394000/dde97e0e-be01-11e5-93b6-38880b60e295.gif)

**Comment by sichvoge** [comment]
Can you post a RAML that does produce that error, pls?

**Comment by qutwala** [comment]
Please see GIF.

**Comment by sichvoge** [comment]
Thank you! That helps a lot.

**Comment by blakeembrey** [comment]
This seems more like it'd be an issue with Atom than the console.
